# Generated by Django 4.2 on 2023-09-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, default='students/student-default.png', upload_to='students/', verbose_name='Фото')),
                ('date_of_birth', models.DateField(verbose_name='Дата Рождения')),
                ('date_of_conclusion', models.DateField(verbose_name='Дата заключения')),
                ('accused', models.TextField(verbose_name='Обвиняется')),
                ('judgment', models.TextField(max_length=200, verbose_name='Присудили')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.SmallIntegerField(choices=[(0, 'Полностью отбыл наказание'), (1, 'Отбывает наказание')], verbose_name='Статус заключения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Студэнт',
                'verbose_name_plural': 'Студэнты',
            },
        ),
    ]
