# Generated by Django 4.2 on 2023-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accused_be',
            field=models.TextField(null=True, verbose_name='Обвиняется'),
        ),
        migrations.AddField(
            model_name='student',
            name='accused_en',
            field=models.TextField(null=True, verbose_name='Обвиняется'),
        ),
        migrations.AddField(
            model_name='student',
            name='description_be',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='student',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='student',
            name='judgment_be',
            field=models.TextField(max_length=200, null=True, verbose_name='Присудили'),
        ),
        migrations.AddField(
            model_name='student',
            name='judgment_en',
            field=models.TextField(max_length=200, null=True, verbose_name='Присудили'),
        ),
        migrations.AddField(
            model_name='student',
            name='name_be',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic_be',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='student',
            name='status_be',
            field=models.SmallIntegerField(choices=[(0, 'Полностью отбыл наказание'), (1, 'Отбывает наказание')], null=True, verbose_name='Статус заключения'),
        ),
        migrations.AddField(
            model_name='student',
            name='status_en',
            field=models.SmallIntegerField(choices=[(0, 'Полностью отбыл наказание'), (1, 'Отбывает наказание')], null=True, verbose_name='Статус заключения'),
        ),
        migrations.AddField(
            model_name='student',
            name='surname_be',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='student',
            name='surname_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
    ]
